#******************************************************************************
# The MIT License (MIT)
#  
# Copyright (c) 2015 Neustar Inc.
#  
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#  
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#  
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#******************************************************************************
#
# $Id: Makefile,v 1.2 2006/03/01 01:35:38 wtan Exp $
#
# This is the Makefile for building EPP Java Implementation
#
# Makefile for directory src/com/neulevel/epp/core/command

TARGETS = EppCommand.class \
          EppCommandLogin.class \
          EppCommandLogout.class \
          EppCommandPoll.class \
          EppCommandInfo.class \
          EppCommandInfoContact.class \
          EppCommandInfoDomain.class \
          EppCommandInfoHost.class \
          EppCommandInfoSvcsub.class \
          EppCommandCreate.class \
          EppCommandCheck.class \
          EppCommandCheckContact.class \
          EppCommandCheckDomain.class \
          EppCommandCheckHost.class \
          EppCommandCheckSvcsub.class \
          EppCommandDelete.class \
          EppCommandDeleteContact.class \
          EppCommandDeleteDomain.class \
          EppCommandDeleteHost.class \
          EppCommandDeleteSvcsub.class \
          EppCommandRenew.class \
          EppCommandRenewDomain.class \
          EppCommandRenewSvcsub.class \
          EppCommandUpdate.class \
          EppCommandUpdateContact.class \
          EppCommandUpdateDomain.class \
          EppCommandUpdateHost.class \
          EppCommandUpdateSvcsub.class \
          EppCommandTransfer.class \
          EppCommandTransferContact.class \
          EppCommandTransferDomain.class \
          EppCommandTransferSvcsub.class \
          EppCreds.class \
          EppCredsOptions.class

DIRS = 
TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
