#******************************************************************************
# The MIT License (MIT)
#  
# Copyright (c) 2015 Neustar Inc.
#  
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#  
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#  
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#******************************************************************************
#
# $Id: Makefile,v 1.2 2006/03/01 01:35:38 wtan Exp $
#
# This is the Makefile for building EPP C++ Implementation
#
# Makefile for directory src/epp/core/command

TOP=../../../..
DIRS=
include $(TOP)/src/Makefile.plat

OBJS=\
	EppCreds.$(O)	\
	EppCredsOptions.$(O)	\
	EppCommand.$(O)	\
	EppCommandLogin.$(O)	\
	EppCommandLogout.$(O)	\
	EppCommandPoll.$(O)	\
	EppCommandCreate.$(O)	\
	EppCommandDelete.$(O)	\
	EppCommandDeleteContact.$(O)	\
	EppCommandDeleteDomain.$(O)	\
	EppCommandDeleteHost.$(O)	\
	EppCommandDeleteSvcsub.$(O)	\
	EppCommandInfo.$(O)	\
	EppCommandInfoContact.$(O)	\
	EppCommandInfoDomain.$(O)	\
	EppCommandInfoHost.$(O)	\
	EppCommandInfoSvcsub.$(O)	\
	EppCommandCheck.$(O)	\
	EppCommandCheckContact.$(O)	\
	EppCommandCheckDomain.$(O)	\
	EppCommandCheckHost.$(O)	\
	EppCommandCheckSvcsub.$(O)	\
	EppCommandRenew.$(O)	\
	EppCommandRenewDomain.$(O)	\
	EppCommandRenewSvcsub.$(O)	\
	EppCommandTransfer.$(O)	\
	EppCommandTransferContact.$(O)	\
	EppCommandTransferDomain.$(O)	\
	EppCommandTransferSvcsub.$(O)	\
	EppCommandUpdate.$(O)	\
	EppCommandUpdateContact.$(O)	\
	EppCommandUpdateDomain.$(O)	\
	EppCommandUpdateHost.$(O)	\
	EppCommandUpdateSvcsub.$(O)	\

HDRS=\
	EppCreds.hpp	\
	EppCredsOptions.hpp	\
	EppCommand.hpp	\
	EppCommandLogin.hpp	\
	EppCommandLogout.hpp	\
	EppCommandPoll.hpp	\
	EppCommandCreate.hpp	\
	EppCommandDelete.hpp	\
	EppCommandDeleteContact.hpp	\
	EppCommandDeleteDomain.hpp	\
	EppCommandDeleteHost.hpp	\
	EppCommandDeleteSvcsub.hpp	\
	EppCommandInfo.hpp	\
	EppCommandInfoContact.hpp	\
	EppCommandInfoDomain.hpp	\
	EppCommandInfoHost.hpp	\
	EppCommandInfoSvcsub.hpp	\
	EppCommandCheck.hpp	\
	EppCommandCheckContact.hpp	\
	EppCommandCheckDomain.hpp	\
	EppCommandCheckHost.hpp	\
	EppCommandCheckSvcsub.hpp	\
	EppCommandRenew.hpp	\
	EppCommandRenewDomain.hpp	\
	EppCommandRenewSvcsub.hpp	\
	EppCommandTransfer.hpp	\
	EppCommandTransferContact.hpp	\
	EppCommandTransferDomain.hpp	\
	EppCommandTransferSvcsub.hpp	\
	EppCommandUpdate.hpp	\
	EppCommandUpdateContact.hpp	\
	EppCommandUpdateDomain.hpp	\
	EppCommandUpdateHost.hpp	\
	EppCommandUpdateSvcsub.hpp	\

SRCS=\
	EppCreds.cpp	\
	EppCredsOptions.cpp	\
	EppCommand.cpp	\
	EppCommandLogin.cpp	\
	EppCommandLogout.cpp	\
	EppCommandPoll.cpp	\
	EppCommandCreate.cpp	\
	EppCommandDelete.cpp	\
	EppCommandDeleteContact.cpp	\
	EppCommandDeleteDomain.cpp	\
	EppCommandDeleteHost.cpp	\
	EppCommandDeleteSvcsub.cpp	\
	EppCommandInfo.cpp	\
	EppCommandInfoContact.cpp	\
	EppCommandInfoDomain.cpp	\
	EppCommandInfoHost.cpp	\
	EppCommandInfoSvcsub.cpp	\
	EppCommandCheck.cpp	\
	EppCommandCheckContact.cpp	\
	EppCommandCheckDomain.cpp	\
	EppCommandCheckHost.cpp	\
	EppCommandCheckSvcsub.cpp	\
	EppCommandRenew.cpp	\
	EppCommandRenewDomain.cpp	\
	EppCommandRenewSvcsub.cpp	\
	EppCommandTransfer.cpp	\
	EppCommandTransferContact.cpp	\
	EppCommandTransferDomain.cpp	\
	EppCommandTransferSvcsub.cpp	\
	EppCommandUpdate.cpp	\
	EppCommandUpdateContact.cpp	\
	EppCommandUpdateDomain.cpp	\
	EppCommandUpdateHost.cpp	\
	EppCommandUpdateSvcsub.cpp	\

TARGETS=$(OBJS)
include $(TOP)/src/Makefile.incl
