#******************************************************************************
# The MIT License (MIT)
#  
# Copyright (c) 2015 Neustar Inc.
#  
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#  
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#  
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#******************************************************************************
#
# $Id: Makefile,v 1.9 2010/01/04 20:58:37 nseshadr Exp $
#
# This is the Makefile for building EPP Java Implementation
#
# Makefile for directory src/com/neulevel/epp/xri

TARGETS = EppXriTrustee.class \
	  EppXriSocialData.class \
	  EppXriServiceEndpointRule.class \
	  EppXriServiceEndpointType.class \
	  EppXriServiceEndpointPath.class \
	  EppXriServiceEndpointMediaType.class \
	  EppXriServiceEndpoint.class \
	  EppXriURI.class \
	  EppXriRef.class \
	  EppXriSynonym.class \
	  EppXriNumberAttribute.class \
	  EppXriAuthority.class \
	  EppXriNumber.class \
	  EppXriName.class \
	  EppXriService.class \
		EppXriContactData.class\
		EppXriCodeStringVASNVPair.class\
		EppXriCodeStringExt.class\
		EppXriResolutionPattern.class\
		EppXriCodeString.class\

DIRS = command response
TOP = ../../../../../
include $(TOP)/src/Makefile.incl
