#******************************************************************************
# The MIT License (MIT)
#  
# Copyright (c) 2015 Neustar Inc.
#  
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#  
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#  
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#******************************************************************************
#
# $Id: Makefile,v 1.3 2010/06/11 21:06:11 achowdhu Exp $
#
# This is the Makefile for building EPP Java Implementation
#
# Makefile for directory src/com/neulevel/epp/core

TARGETS = EppEntity.class \
          EppE164.class \
          EppAddress.class \
          EppStatus.class \
          EppAuthInfo.class \
          EppPeriod.class \
          EppIpAddress.class \
          EppContactData.class \
          EppContactDisclose.class \
          EppTransactionId.class \
          EppUnspec.class \
          EppObject.class \
          EppHostAttribute.class \
          EppContactType.class \
          EppContact.class \
          EppDomain.class \
          EppHost.class \
          EppSvcsubParam.class \
          EppSvcsub.class \
          EppHello.class \
          EppDataCollectionStatement.class \
          EppDataCollectionPolicy.class \
          EppGreeting.class \
          EppServiceMenu.class \
          EppPollable.class \
          EppError.class \
          EppParser.class \
          EppUtil.class \
	  EppUnspecNVPairTuple.class \
	  EppGenericNVPairs.class

DIRS = command response
TOP = ../../../../..
include $(TOP)/src/Makefile.incl
