#******************************************************************************
# The MIT License (MIT)
#  
# Copyright (c) 2015 Neustar Inc.
#  
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#  
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#  
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#******************************************************************************
#
# $Id: Makefile,v 1.3 2007/10/15 19:03:12 wtan Exp $
#
# This is the Makefile for building EPP C++ Implementation
#
# Makefile for directory src/epp/core/response

TOP=../../../..
DIRS=
include $(TOP)/src/Makefile.plat

OBJS=\
	EppResultMessage.$(O)	\
	EppValueReason.$(O)	\
	EppResult.$(O)	\
	EppResponse.$(O)	\
	EppResponseData.$(O)	\
	EppResponseDataCreate.$(O)	\
	EppResponseDataCreateContact.$(O)	\
	EppResponseDataCreateDomain.$(O)	\
	EppResponseDataCreateHost.$(O)	\
	EppResponseDataCreateSvcsub.$(O)	\
	EppResponseDataInfo.$(O)	\
	EppResponseDataCheck.$(O)	\
	EppResponseDataCheckContact.$(O)	\
	EppResponseDataCheckDomain.$(O)	\
	EppResponseDataCheckHost.$(O)	\
	EppResponseDataCheckSvcsub.$(O)	\
	EppResponseDataPending.$(O)	\
	EppResponseDataPendingContact.$(O)	\
	EppResponseDataPendingDomain.$(O)	\
	EppResponseDataPendingHost.$(O)	\
	EppResponseDataPendingSvcsub.$(O)	\
	EppResponseDataPoll.$(O)	\
	EppResponseDataRenew.$(O)	\
	EppResponseDataRenewDomain.$(O)	\
	EppResponseDataRenewSvcsub.$(O)	\
	EppResponseDataTransfer.$(O)	\
	EppResponseDataTransferContact.$(O)	\
	EppResponseDataTransferDomain.$(O)	\
	EppResponseDataTransferSvcsub.$(O)	\
	EppResponseDataNeustarTransaction.$(O)	\
	EppReason.$(O)	\

HDRS=\
	EppResultMessage.hpp	\
	EppValueReason.hpp	\
	EppResult.hpp	\
	EppResponse.hpp	\
	EppResponseData.hpp	\
	EppResponseDataCreate.hpp	\
	EppResponseDataCreateContact.hpp	\
	EppResponseDataCreateDomain.hpp	\
	EppResponseDataCreateHost.hpp	\
	EppResponseDataCreateSvcsub.hpp	\
	EppResponseDataInfo.hpp	\
	EppResponseDataCheck.hpp	\
	EppResponseDataCheckContact.hpp	\
	EppResponseDataCheckDomain.hpp	\
	EppResponseDataCheckHost.hpp	\
	EppResponseDataCheckSvcsub.hpp	\
	EppResponseDataPending.hpp	\
	EppResponseDataPendingContact.hpp	\
	EppResponseDataPendingDomain.hpp	\
	EppResponseDataPendingHost.hpp	\
	EppResponseDataPendingSvcsub.hpp	\
	EppResponseDataPoll.hpp	\
	EppResponseDataRenew.hpp	\
	EppResponseDataRenewDomain.hpp	\
	EppResponseDataRenewSvcsub.hpp	\
	EppResponseDataTransfer.hpp	\
	EppResponseDataTransferContact.hpp	\
	EppResponseDataTransferDomain.hpp	\
	EppResponseDataTransferSvcsub.hpp	\
	EppResponseDataNeustarTransaction.hpp	\
	EppReason.hpp	\

SRCS=\
	EppResultMessage.cpp	\
	EppValueReason.cpp	\
	EppResult.cpp	\
	EppResponse.cpp	\
	EppResponseData.cpp	\
	EppResponseDataCreate.cpp	\
	EppResponseDataCreateContact.cpp	\
	EppResponseDataCreateDomain.cpp	\
	EppResponseDataCreateHost.cpp	\
	EppResponseDataCreateSvcsub.cpp	\
	EppResponseDataInfo.cpp	\
	EppResponseDataCheck.cpp	\
	EppResponseDataCheckContact.cpp	\
	EppResponseDataCheckDomain.cpp	\
	EppResponseDataCheckHost.cpp	\
	EppResponseDataCheckSvcsub.cpp	\
	EppResponseDataPending.cpp	\
	EppResponseDataPendingContact.cpp	\
	EppResponseDataPendingDomain.cpp	\
	EppResponseDataPendingHost.cpp	\
	EppResponseDataPendingSvcsub.cpp	\
	EppResponseDataPoll.cpp	\
	EppResponseDataRenew.cpp	\
	EppResponseDataRenewDomain.cpp	\
	EppResponseDataRenewSvcsub.cpp	\
	EppResponseDataTransfer.cpp	\
	EppResponseDataTransferContact.cpp	\
	EppResponseDataTransferDomain.cpp	\
	EppResponseDataTransferSvcsub.cpp	\
	EppResponseDataNeustarTransaction.cpp	\
	EppReason.cpp	\

TARGETS=$(OBJS)
include $(TOP)/src/Makefile.incl
